name: Preview Deploy

on:
  push:
    branches-ignore:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run build
        run: bun run build
      - name: Typcheck
        run: bun run check
      - name: Deploy to Vercel
        working-directory: ./www
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
